### PR TITLE
Protocol 19, bulk_pull ascending, remove vote_by_block

### PR DESCRIPTION
**Pull request by dsiganos**
* Add support for bulk_pull_ascending_flag
* Protocol v19
* Add makefile for generating the diagram.
* Drop support for confirm_ack with block payload (vote by block)

### CODE REVIEW

**Comment by dsiganos** [comment]
@cryptocode , it would be great if you could do a quick review since you know Kaitai best. Thanks.

**Review by fikumikudev — APPROVED** [review]
I only worked with Kaitai a little bit, looks good to me. I like the addition of Makefile, maybe in the future we can setup a CI pipeline of some sort.

**Comment by cryptocode** [comment]
> @cryptocode , it would be great if you could do a quick review since you know Kaitai best. Thanks.

Looks good, maybe just update the `msg_confirm_ack` doc to reflect that it's only vote-by-hash now.

**Comment by dsiganos** [comment]
> > @cryptocode , it would be great if you could do a quick review since you know Kaitai best. Thanks.
> 
> Looks good, maybe just update the `msg_confirm_ack` doc to reflect that it's only vote-by-hash now.

Done. Thank you.

**Pull request merged**
